export enum Configuration {
  PORT = 'PORT',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_NAME = 'DB_NAME',
  DB_CONNECTION_READ = 'DB_CONNECTION_READ',
  DB_CONNECTION_WRITE = 'DB_CONNECTION_WRITE',
  DB_READ_PASS = 'DB_READ_PASS',
  DB_WRITE_PASS = 'DB_WRITE_PASS',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
}
